### ISSUE TITLE
Add support for private builds

### ISSUE THREAD

**Issue by brycekahle** [sosedoff/travis-github#2]
I'd be happy to contribute this, but wanted to chat about it first. I'm thinking if no public builds come back AND you have a Travis API token configured (extension config would need to added), then the extension could hit `https://api.travis-ci.com` instead?

**Comment by sosedoff** [comment]
It could. Here are my thoughts on this: when configuring the extension with travis CI token it should pull the list of private projects and save the ids/names into localstorage. Then check whether the project is private or public and then use a corresponding API endpoint.

**Comment by hkdobrev** [comment]
@sosedoff I guess there's no reason to keep the list of private projects. Just query `api.travis-ci.com` directly with the token if the repo is private.

**Comment by brycekahle** [comment]
@hkdobrev Ah true! We can look at the classes on `h1.entry-title` and see if it is `public` or `private`.

**Comment by sosedoff** [comment]
@hkdobrev good point, i forgot that github adds a special label on the page if the project is private

**Comment by hkdobrev** [comment]
I'm using that together with https://github.com/sindresorhus/refined-github where I'm collaborating and I'm now used to spotting quite a lot of useful details in GitHub.com DOM. :laughing:
